### ISSUE TITLE
Error saving to Wallabag (400)

### ISSUE THREAD

**Issue by bobberb** [joshp23/ttrss-to-wallabag-v2#11]
Dear @joshp23 

I am currently trying to move my tt-rss from the clue/docker-ttrss ubuntu-based image to an alpine based image. The dockerfile I am using is linked [here](http://pastebin.com/QREwi1sZ)

I build just fine and ttrss finds and enables the plugin. My wallabag credentials are unchanged. All works normally except for the submission which returns the 400. 

Any help would be appreciated, let me know if I can provide any further detail.

**Comment by bobberb** [comment]
now it returns 0 on a new docker start...

**Comment by bobberb** [comment]
Update:

My firewall was blocking all incoming connections from my docker virtual networks, facepalm.

Please delete this issue at your discretion.

**Comment by joshp23** [comment]
Glad it worked out! I'm keeping this here. I'm sure someone will benefit from this!

**Comment by 4oo4** [comment]
Also just wanted to add that the Wallabag API gives an HTTP 400 for bad authentication :smile:
