### ISSUE TITLE
Parse error due to version 1.0.1

### ISSUE THREAD

**Issue by AS-dh** [joshp23/ttrss-to-wallabag-v2#14]
Apparently the recent change to let the version be 1.0.1 leads to a syntax error. I get:

Parse error: syntax error, unexpected '.1' (T_DNUMBER), expecting ')' in /tt-rss/plugins.local/wallabag_v2/init.php on line 6

when trying to load the plugins in the preferences.
I'm not a programmer but was able to get rid of the error by putting the number in quotes "1.0.1"

Thanks for the nice plugin!

**Comment by joshp23** [comment]
fixed with latest. thanks
