### ISSUE TITLE
Unescape password string after retrieval

### ISSUE THREAD

**Issue by Glandos** [joshp23/ttrss-to-wallabag-v2#17]
I saw that the password is stored using `db_escape_string`. Since my password contains a `'` and I'm using postgresql, this result in a double `''` in the storage. However, this double character is not de-doubled when requesting wallabag.
I've tried to found if there is such things as `unescape`, without success. Maybe it's hidden in TT-rss…

**Comment by Glandos** [comment]
I've found it. You should not escape strings, since it is already done here : https://tt-rss.org/gitlab/fox/tt-rss/blob/master/classes/pluginhost.php#L314 So there is a double escape.
Yes, I know, a lot of old plugins does this, e.g. the mail plugin.

You should remove db_string_escape before saving, and be sure that I am right!

**Comment by joshp23** [comment]
nice find. I'll take a look at this as time permits

**Comment by Nicocys** [comment]
That seems to work: I removed every mention of db_escape_string in the save() function of init.php, and I can finally save articles to wallabag.

**Comment by joshp23** [comment]
Send me a pull request if you can and I'll merge it in.

**Comment by Nicocys** [comment]
Done. It's untested, as in I just tried to save to wallabag, and it worked, but I'm the sole user of my installation, so no security check or anything like that.

**Comment by joshp23** [comment]
this has been merged, thanks!
