### ISSUE TITLE
Error saving to Wallabag!: (400)

### ISSUE THREAD

**Issue by ivantomica** [joshp23/ttrss-to-wallabag-v2#19]
After creating API client and obtaining Client ID and Client secret parameters and populating those within settings of Wallabag v2 plugin I get the following error when pressing on Wallabag button below the article:

`Error saving to Wallabag!: (400)`

No additional message is given. Any ideas on what might be wrong? Is plugin working for you properly with latest TTRSS instance?

**Comment by bobberb** [comment]
Have you tried doing this API call manually?

**Comment by ivantomica** [comment]
No, I'm not quite sure how to do that. Would you be so kind to provide an example of command (PHP preferably, so it can be run from the command line interpreter)?

**Comment by bobberb** [comment]
I am not familiar with php.

Since you mention the command line, I assume you have curl installed. I
recommend the easier to use curl abstractor https://httpie.org.

You will need to pass the username, password, and the client ID and secret
to curl/httpie to receive the Authorization token. With this token, you can
use the API to add/edit wallabag entries, for example:


#!/bin/bash
for i in {23..563}
do
http PATCH http://localhost:8885/api/entries/$i/reload
"Authorization:Bearer
NGU0YmI2Yzk4ZTBjMzNmMWQ3NWM1OGVhNjk0MGZjNWVkNzIxYjVhNzMwOGQxNzQxMGQwZTI3M2M3ZWI2YjhmYQ"
                                                                 done


Will iterate through articles 23-563 and re-download them. Adjust as per
the v2 API sheet.


Apologies for formatting, I'm on a phone.

**Comment by joshp23** [comment]
Everything is working fine for me. 

I wonder if you filled out _every_ section of the Wallabag configuration in the plugin? With the minimal information that you have, there is little I can do. 

Perhaps enter dev mode in your browser and check the console for feedback, or look in your server logs after making sure error reporting is on. These are two great places to start debugging.

If not, then you have to check your Wallabag API manually. You may want to have a read through [this relevant section](https://doc.wallabag.org/en/developer/api/readme.html) of the wallabag docs, and maybe keep [this bit](http://v2.wallabag.org/api/doc) on hand as well. You can send requests to the API directly from a terminal, it's handy.

If you need some inspiration _beyond the above links_, or if you just are that attached to testing in PHP while playing with the API, look at [this plugin's oath script](https://github.com/joshp23/ttrss-to-wallabag-v2/blob/master/wallabag_v2/oauth.php), and maybe [the spare parts](https://github.com/joshp23/ttrss-to-wallabag-v2/blob/master/spare_parts/oauth.refresh.php).

Also, keep in mind that, [as others have pointed out](https://github.com/joshp23/ttrss-to-wallabag-v2/issues/11#issuecomment-300529414), Wallabag will throw a 400 error when you hit the API with bad credentials. In that same issue thread someone noticed that there firewall was a part of the issue. So scan your environment.

UPDATED

**Comment by ivantomica** [comment]
> I wonder if you filled out every section of the Wallabag configuration in the plugin? With the minimal information that you have, there is little I can do.
 
Yes. 

> Perhaps enter dev mode in your browser and check the console for feedback, or look in your server logs after making sure error reporting is on. These are two great places to start debugging.

Nothing in logs on either vhosts on the server. Console is also being empty, or I don't know how to use it properly as It is not something I work with.

> as others have pointed out

Links leads to api documentation of the wallabag, I believe you wanted to link to some forum thread, can you please update or send me an link so I can look for a further troubleshooting inspiration there?

Feel free to close the issue afterwards. Thank you for the assistance.

**Comment by ivantomica** [comment]
As it usually goes with such issues, issue was classic example of PEBKAC. Anyhow, issue was resolved by changing password on the Wallabag instance to the less complex one. 

Previous password was 32 characters long containing following special characters which might have caused the issue when trying to post request to wallabag instance (not properly escaped):

`.\][|>(`

**Comment by joshp23** [comment]
escaping is a [known issue](https://github.com/joshp23/ttrss-to-wallabag-v2/issues/17), so not entirely PEBKAC. I haven't had time to test, and no pull requests have come in to fix it.
