### ISSUE TITLE
MySQL database errors

### ISSUE THREAD

**Issue by ghost** [joshp23/ttrss-to-wallabag-v2#21]
I am seeing these errors in the system log of tt-rss.
Something to do with the recent tt-rss database connector update ?

Legacy connect requested to mysql
1. classes/db.php(22): user_error(Legacy connect requested to mysql, 1024)
2. classes/db.php(89): legacy_connect()
3. include/db.php(4): get()
4. plugins.local/wallabag_v2/init.php(98): db_escape_string(169961)
5. classes/pluginhandler.php(12): getwallabagInfo()
6. backend.php(126): catchall(getwallabaginfo)

**Comment by joshp23** [comment]
If I have time... Grad school has me pretty busy. Feel free to open a pull request if you can address this before I can.

**Comment by joshp23** [comment]
Fixed with 9f0203a and in the [latest release](https://github.com/joshp23/ttrss-to-wallabag-v2/releases/tag/1.0.4)

**Comment by ghost** [comment]
Thank you.

**Comment by bobberb** [comment]
Thank you!!
