### ISSUE TITLE
Random fail... null tokens

### ISSUE THREAD

**Issue by joshp23** [joshp23/ttrss-to-wallabag-v2#23]
I had a random hang and fail on my installation when trying to save an article to Wallabag. I tried a second, random article, and it failed quickly with the, "Go configure..." error. I checked the DB and sure enough the tokens were showing an `N` value... but there was an access token timeout value, curiously enough.

Problem was resolved by re-entering the user:password to this plugin's configuration, and obtaining a new token set. Tokens are refreshing properly again, etc. Not able to reproduce error.

It had been a few days since I tried to save to Wallabag with this plugin, so I'm thinking that there was a cURL call to refresh the token that hung due to network issues or something, and no return values were sent, resulting in a `null` value when saving the new token data.

**Comment by joshp23** [comment]
It's clear that there needs to be a catch for an error on return for this call.

**Comment by joshp23** [comment]
Most cases encountering this will be resolved with the restructured token logic with cf71533. Still need to add in something to address a cURL timeout when making calls to handle the rest.

**Comment by joshp23** [comment]
attempted to address this by adding timeouts to token calls with  2195e70

**Comment by joshp23** [comment]
This is still happening. The plugin will randomly delete the oauth tokens. I assume that it is doing this on a failed refresh, likely due to networking errors. I am working on adding in some debug code.

**Comment by joshp23** [comment]
e68b0b7 keeps the plugin from saving null token data. I have to expand on this to handle that failure in a more robust way. Currently, it just skips saving, and debug data will be spat out. Also, a lot of debug data will now be spat out.

**Comment by joshp23** [comment]
FINALLY! I got some useful debug info from this fail:
```
{   
    "wallabag_url":"https:\/\/wallabag.example.com",
     "title":"Science and Buddhism",
     "auth_status":400,
     "auth_error":"invalid_grant",
     "auth_error_msg":"Refresh token has expired",  <<<
     "error":null,
     "error_msg":null,
     "refresh_token":null,
     "access_token":null,
     "auth_type":"refreshed",  <<<
     "status":401
}
```
The two lines marked `<<<` indicate that the refresh tokens aren't, in fact, eternal, and must be refreshed themselves, *sigh*. This just means an additional loop must be put in when this error comes back on refresh, and everything will be 100%

**Comment by joshp23** [comment]
A Wallabag refresh token lives for [2 weeks](https://github.com/wallabag/wallabag/blob/master/app/config/config.yml#L198). Fix soon to come.

**Comment by bobberb** [comment]
Haha cheers mate, let me pull this one down...

**Comment by bobberb** [comment]
Working perfectly.
