### ISSUE TITLE
Error after upgrading to PHP 7

### ISSUE THREAD

**Issue by dariottolo** [joshp23/ttrss-to-wallabag-v2#24]
Dear all,

I am having issues with the plugin, since I upgraded to PHP 7.1

The articles are correctly saved into wallabag, but I find this errors in the  ttrss_error_log table:

`-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Creato il: Mar 13, 2018 alle 21:17
-- Versione del server: 10.0.34-MariaDB-cll-lve

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: diludovi_rss
--

--
-- Dump dei dati per la tabella ttrss_error_log
--

INSERT INTO ttrss_error_log (id, owner_uid, errno, errstr, filename, lineno, `context`, created_at) VALUES
(63, 2, 1024, 'Legacy connect requested to mysql', 'classes/db.php', 22, '1. classes/db.php(22): user_error(Legacy connect requested to mysql, 1024)\n2. classes/db.php(89): legacy_connect()\n3. include/db.php(4): get()\n4. plugins.local/wallabag_v2/init.php(98): db_escape_string(57560)\n5. classes/pluginhandler.php(12): getwallabagInfo()\n6. backend.php(126): catchall(getwallabaginfo)\n', '2018-03-13 16:37:24');
`
tt-rss is git updated to the latest version.
Wallabag version is 2.3.1
I am on a shared hosting

I believe some PHP extension is missing, but I do not know which one.

Thanks a lot in advance.

Regards

**Comment by joshp23** [comment]
Refer to issue #21 which was addressed with release 1.0.4

**Comment by dariottolo** [comment]
I upgraded and it seems to be working perfectly. Sorry for wasting your time.

**Comment by joshp23** [comment]
Pay special attention to the reference to

 plugins.local/wallabag_v2/in it.pho(98):db_escape_string

This is not present since 1.0.4

Update your plugin ;)

**Comment by joshp23** [comment]
Glad you found the error
