### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by bobberb** [joshp23/ttrss-to-wallabag-v2#27]
On a fresh install of ttrss 17.12 (docker from linuxserver.io) and a pull of the master.zip, I am now unable to save credentials. Clicking save does nothing.

**Comment by bobberb** [comment]
Sorry, should have read #23 -- debug.txt simply gives me "null" as well.

**Comment by joshp23** [comment]
I will have to attempt to reproduce this error. I'm using latest from master with a fully updated ttrss and everything works as expected aside from #23, which doesn't effect generating the initial token. For brevity, #23 is due to failing to handle stale refresh tokens (which I didn't realize were a thing). The workaround for that is to re-generate tokens by resaving in pref.

I'm hearing that you can't generate initial tokens at all? Could you clarify that? If so, I'm wondering what is in your sql database, did client id and secret save along with the wallabag url?

Also, is there any more data in debug.txt? If so, please post it, and I will get to this as I can. 

You can try using an earlier release as well. If one works please let me know.

**Comment by bobberb** [comment]
I am using postgres 9.6 with the linuxserver.io docker image. I will switch to a different image and see if that solves it.

Cannot generate initial tokens, this is correct. Client ID and secret do indeed save (they survive a refresh, if that's my indication).

Debug.txt is just timestamp + null line after line. 

Will also try an earlier release before following up.

**Comment by bobberb** [comment]
I'm wondering now if this is a wallabag issue:
Reverted to release 1.1.0:

* Able to save credentials but unable to save articles. Would love to assist you in any way I can, can I enable some more verbose outputs?

**Comment by joshp23** [comment]
> I'm wondering now if this is a wallabag issue:

Same, this is very odd behavior from your install. I am going to delete my plugin database and reinstall the plugin and see what I get. i just pulled ttrss so it is fully up to date. 

on 1.1.0 in init.php there are several commented out lines that, when uncommented, might provide some useful data in the browser console. lines 113, 123, 132, and 178 - 182.

**Comment by joshp23** [comment]
just a thought, have you tried to issue requests to wallabag's apu via curl in the terminal from your server?

**Comment by bobberb** [comment]
Yes. I was prompted to reload every wallabag article last night when I exported all my articles to make my switch from mariadb to postgresql. I can definitely hit the api successfully. 


As of 21:00 5/21:
* Deleted my existing ttrss docker
* Pulled down https://github.com/talmai/docker-ttrss/
* Ran using params:

`docker run -it -p 8887:5000 \
-e DB_TYPE=pgsql \
-e DB_PORT=5432 \
-e DB_HOST=10.0.0.9 \
-e DB_NAME=ttrss \
-e DB_USER=ttrss \
-e DB_PASS=ttrss \
-e HOST_URL=http://127.0.0.1:8887 \
-v /tank/selfhosted/ttrss/plugins.local:/app/htdocs/plugins.local \
talmai/docker-ttrss`


ttrss DB was connected to and ttrss resumes as normal.

Tested:
1.1.0: States "ready to send articles to wallabag" - fails immediately on attempt to send to wallabag. Commenting out all those lines above causes the image not to boot/respond/hang (unclear). 
1.4.0: Input all fields in plugin, click save, after 30 seconds I receive a blue "null" popup bar (no debug.txt written).

**Comment by bobberb** [comment]
When I commented out those lines above I was unable to even reach the website and had to re-unzip the plugin to overwrite my changes.

**Comment by bobberb** [comment]
Downgraded to 1.0.4 - states "Ready to send" even with all empty fields - maybe I should just drop the whole database?

**Comment by joshp23** [comment]
This makes no sense to me...

**Comment by bobberb** [comment]
Solved.

ttrss/plugin/wallabag didn't like me going through my LAN - now I point to my https://wallabag.domain.org and it's working perfectly on master pull.
