### ISSUE TITLE
Plugin not saving, after configured

### ISSUE THREAD

**Issue by andre-m-faria** [joshp23/ttrss-to-wallabag-v2#29]
After configurating the plugin it show the following message.

> The Wallabag_v2 plugin needs to be configured. See the README for help

I had to change the Client ID and Client Secret because of new installation of wallabag

**Comment by andre-m-faria** [comment]
debug.txt content

`{"wallabag_url":"https:\/\/albacore.cdx.local\/wallabag","title":"Dell Debuts First 49-Inch Monitor With Dual QHD Resolution DONT PUBLISH","status":0,"auth_type":"old","auth_status":null,"auth_error":null,"auth_error_msg":null,"error":null,"error_msg":null,"refresh_token":null,"access_token":"MWIyZjA5NDI1Zjc1ZWE5NzZiMjRhOTRjZWY5YmUzY2M2MWE5Y2Q3ODA5Y2U3ZWM1MWVkNGZlNWVkZTY1YmVlMw"}`

**Comment by andre-faria** [comment]
```
POST /oauth/v2/token HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 224
Content-Type: application/json
Host: albacore.cdx.local
User-Agent: HTTPie/0.9.2

{
    "client_Id": "2_4znx5dahz50kkcws80wwk0g8kws0gwso08sg848gs4c0kowkcs",
    "client_secret": "4h1uceidjsis0ococs44wss8s0wkkk4ckkocs00cw4so840c8k",
    "grant_type": "password",
    "password": "PASSWORD",
    "username": "USERNAME"
}

HTTP/1.1 404 Not Found
Connection: Keep-Alive
Content-Length: 297
Content-Type: text/html; charset=iso-8859-1
Date: Mon, 15 Oct 2018 13:43:54 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /oauth/v2/token was not found on this server.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at albacore.cdx.local Port 443</address>
</body></html>

```

**Comment by andre-m-faria** [comment]
```
POST /wallabag/oauth/v2/token HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 224
Content-Type: application/json
Host: albacore.cdx.local
User-Agent: HTTPie/0.9.2

{
    "client_Id": "2_4znx5dahz50kkcws80wwk0g8kws0gwso08sg848gs4c0kowkcs",
    "client_secret": "4h1uceidjsis0ococs44wss8s0wkkk4ckkocs00cw4so840c8k",
    "grant_type": "password",
    "password": "PASSWORD",
    "username": "USERNAME"
}

HTTP/1.1 400 Bad Request
Cache-Control: no-store, private
Connection: close
Content-Length: 95
Content-Type: application/json
Date: Mon, 15 Oct 2018 13:46:07 GMT
Pragma: no-cache
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "error": "invalid_client",
    "error_description": "Client id was not found in the headers or body"
}
```

**Comment by joshp23** [comment]
Hi, just a note, I am using the latest versions of this plugin, and both apps, and I cannot reproduce the error. But I did notice above that you have `client_Id: SOME-ID` where it might be better set to `client_id: SOME-ID`

**Comment by andre-m-faria** [comment]
Damn it! You was right, was because the uppercase letter, so why the hell I'm getting this message while using the plugin, can you help me troubleshoot ?
The Wallabag_v2 plugin needs to be configured. See the README for help

```
HTTP/1.1 200 OK
Cache-Control: no-store, private
Connection: Keep-Alive
Content-Length: 263
Content-Type: application/json
Date: Mon, 15 Oct 2018 16:38:01 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "access_token": "MzlmNWRlMzBkZjViZTVmNzQ3ZWE2ZmNiODdlZTAzNmM0ZDkxMjk1ZTJlMGQyMmVmODFmYjA4NTYxZDc3ZTRjOQ",
    "expires_in": 3600,
    "refresh_token": "MmM3Y2E5YzM5ZDMxYjBhMGFkZDcwODIyNWQxOGE3NWRjMTg2ZTg0ZmUzZmU4ZjY1NGFmZGRlZDIzYjAwNTVmNA",
    "scope": null,
    "token_type": "bearer"
}
```

**Comment by joshp23** [comment]
Looking at your debug.txt data, it looks like you might benefit from entering into the plugin settings in ttrss, and resetting the token by submitting the form data without username and password one time, then re-entering the user name and password. I know it's a cumbersome way to do that, but it seems like it might solve your issue

**Comment by andre-m-faria** [comment]
@joshp23 I already sent it in blank, I was thinking about this, there is another way to reset it?
Because I've already removed the plugin, move it to /plugins folder, used another credentials, and NOTHING works!

**Comment by joshp23** [comment]
You could delete the `Wallabag_v2` column in the `plugin_storage` table in ttrss's database, or edit that column to remove the relevant data.

**Comment by joshp23** [comment]
incidentally, `"status":0` seems to suggest a network issue.

**Comment by joshp23** [comment]
There's no error code being returned, just... nothing

**Comment by andre-m-faria** [comment]
> incidentally, `"status":0` seems to suggest a network issue.

TT-RSS and Wallabag are installed in same environment.

**Comment by andre-m-faria** [comment]
`|  5 | Wallabag_v2    |         1 | a:9:{s:21:"wallabag_access_token";N;s:29:"wallabag_access_token_timeout";i:1539626757;s:22:"wallabag_refresh_token";N;s:30:"wallabag_refresh_token_timeout";i:1540832757;s:17:"wallabag_username";s:6:"USERNAME";s:17:"wallabag_password";s:20:"PASSWORD";s:12:"wallabag_url";s:35:"https://albacore.cdx.local/wallabag";s:18:"wallabag_client_id";s:52:"2_4znx5dahz50kkcws80wwk0g8kws0gwso08sg848gs4c0kowkcs";s:22:"wallabag_client_secret";s:50:"4h1uceidjsis0ococs44wss8s0wkkk4ckkocs00cw4so840c8k";} |
`

**Comment by andre-m-faria** [comment]
Worked after I changed Wallabag to HTTP, It's possible that this is happening because I'm using a self-signed certificate?

**Comment by joshp23** [comment]
> | 5 | Wallabag_v2 | 1 | a:9:{s:21:"wallabag_access_token";N;s:29:"wallabag_access_token_timeout";i:1539626757;s:22:"wallabag_refresh_token";N;s:30:"wallabag_refresh_token_timeout";i:1540832757;s:17:"wallabag_username";s:6:"USERNAME";s:17:"wallabag_password";s:20:"PASSWORD";s:12:"wallabag_url";s:35:"[https://albacore.cdx.local/wallabag";s:18:"wallabag_client_id";s:52:"2_4znx5dahz50kkcws80wwk0g8kws0gwso08sg848gs4c0kowkcs";s:22:"wallabag_client_secret";s:50:"4h1uceidjsis0ococs44wss8s0wkkk4ckkocs00cw4so840c8k";}](https://albacore.cdx.local/wallabag%22;s:18:%22wallabag_client_id%22;s:52:%222_4znx5dahz50kkcws80wwk0g8kws0gwso08sg848gs4c0kowkcs%22;s:22:%22wallabag_client_secret%22;s:50:%224h1uceidjsis0ococs44wss8s0wkkk4ckkocs00cw4so840c8k%22;%7D) |

That appears to be from the database? If so, there is no access token in that, and no refresh token. You should be able to re-enter your user name and password to collect tokens from wallabag. If that does not work, then your installation is not reaching wallabag for some reason. 

For brevity, the `status` element in `debug.txt` is generated at line 288 and of `init.php`. It looks like this:
```
$status = curl_getinfo($cURL, CURLINFO_HTTP_CODE);
```
If a `null` or ``0 value is returned, then the explanation is connectivity. See [this](https://stackoverflow.com/questions/10227879/php-curl-http-code-return-0/10228476#10228476) for a brief explanation.

**Comment by joshp23** [comment]
It is quite possible, it would appear as if your self singed cert is not trusted by your curl installation. There's a lot of info on this issue, perhaps see [here](https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list) for some tips on importing your certificate into system trust. See [here](https://stackoverflow.com/a/15237205/6204776) for disabling curl's ssl verification (not recommended).

Glad you sorted the issue.

**Comment by andre-m-faria** [comment]
Thanks for you help and time!
