### ISSUE TITLE
Saving to Wallabag throws a 404 error

### ISSUE THREAD

**Issue by ddeimeke** [joshp23/ttrss-to-wallabag-v2#3]
I created a new client - redirect URI: https://lenim.mhochzwei.net/ttr/ - in my Wallabag instance - https://wallabag.deimeke.net/ - and configured the plugin accordingly.

Wenn I try to save to Wallabag I gent an 404 error every time.

What could be wrong?

**Comment by ddeimeke** [comment]
Found it. The URL - neither of Tiny Tiny RSS nor of Wallabag - should not end with a slash.

**Comment by joshp23** [comment]
I will add that to the instructions.
