### ISSUE TITLE
ttrss-to-wallabag-v2 overrides plugins-tab in ttrss

### ISSUE THREAD

**Issue by Nepochal** [joshp23/ttrss-to-wallabag-v2#31]
Version 1.7.1 of the ttrss-to-wallabag-plugin overrides the default plugins tab in the preferences of ttrss (Preferences -> Preferences -> Plugins).
Without your plugin there is a list of all installed plugins. After installing your plugin, the list is replaced by the config of the plugin (Wallabag URL, Username, Password, Client ID, Client Secret)

**Comment by joshp23** [comment]
looks like I missed some bits when updating to latest. Pull requests are welcome. Day job has me in full effect. I'll check this out when I can.

**Comment by joshp23** [comment]
I cannot reproduce this error on 1.7.1 with ttrss v18.12 (fca78f7)

**Comment by Nepochal** [comment]
As soon as I find time, I will try it again with the current commit of TTRSS and then get back to you again.

**Comment by Nepochal** [comment]
This seemed to be a bug in ttrss. With the current commit of ttrss everything is fine.

**Comment by joshp23** [comment]
glad it worked out
