### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by gumida** [joshp23/ttrss-to-wallabag-v2#33]
Hello,
I've tried to install this plugin for the first time today and got something very similar to #32 and #30.
But since I'm already to the latest TTRSS version and started with  1.8.0 of this plugin, I thought, maybe this could be something different? 

```
ReferenceError: Notify is not defined
    at postArticleToWallabag (https://my.ttrinstallation.com/:526:50)
    at HTMLImageElement.onclick (https://my.ttrinstallation.com/:1:1)
```
Thanks,
gumida

**Comment by gumida** [comment]
Upgraded from tt-rss 18.12 to a current git clone -> seems to be fixed now :smiley:

**Comment by joshp23** [comment]
indeed. significant changes were made to tt-rss base code regarding Javascript handling of things like notify, and other ui functions. I should update the Readme when/if I get time.
