### ISSUE TITLE
ReferenceError:

### ISSUE THREAD

**Issue by partymike** [joshp23/ttrss-to-wallabag-v2#36]
Hi, I get the following error even after updating to the latest version of the plugin 1.8.1 which I can see is referenced in the issues log here to fix this problem:

ReferenceError: Notify is not defined
    at postArticleToWallabag (http://192.xx.xx.x:8085/index.php:614:50)
    at HTMLImageElement.onclick (http://192.xxx.xx.x:8085/index.php#f=-3&c=0:1:1)

Basically I copied the plugin to plugin.local, entered credentials and restarted...have I missed something?

#update - not sure if relevant by I use the linuxserver docker image :-)

**Comment by joshp23** [comment]
My guess is that the version of Tt-rss from that docket image is not up to date. What version is it?

**Comment by partymike** [comment]
v17.4 it's a linuxserver.io docker, although looking at tt-rss git they show a version 19...but then linuxserver does state the version number on tt-rss is misleading - slightly confusing!

Basically I have the linuxserver docker image with :latest tag :-)

**Comment by joshp23** [comment]
That image is apparently using 2 yr old code. Your option is to use 1.6.0 of this plugin... or use an updated version of TT-RSS. I recommend just learning to install it yourself from git.
