### ISSUE TITLE
No notification saving Wallabag credentials

### ISSUE THREAD

**Issue by ngosang** [joshp23/ttrss-to-wallabag-v2#37]
First of all, thank you for the plugin!
The plugin is working fine for me, but I can't see any notification when I press save.
![image](https://user-images.githubusercontent.com/10577978/63708820-c2e32a00-c835-11e9-9192-ccee78a0311b.png)
![image](https://user-images.githubusercontent.com/10577978/63708852-d1c9dc80-c835-11e9-96e9-ab2147c42171.png)

TT-RSS version: current master 26 august 2019

**Comment by joshp23** [comment]
I've been pulled away from my projects for a few months with a new 9-5. I'll look into this, but I haven't experienced this bug myself. I'm very open to pull requests ;)

**Comment by joshp23** [comment]
got it!
