### ISSUE TITLE
tt-rss share url?

### ISSUE THREAD

**Issue by somedevreally** [joshp23/ttrss-to-wallabag-v2#39]
Hello,

tt-rss have a feature to share an article using plugin called "share" it shares article by its own unique URL
So is it possible to use this url in wallabag, when we add the article? instead of actual website url?

if i have full article locally with tt-rss/database and if wallabag can access it without going on web would it be great idea? is it possible?

Edit: if i manually add the unique url to wallabag it works.
thanks

**Comment by joshp23** [comment]
I don't see the benefit here. 

Wallabag would still
1. have to be contacted by tt-rss
2. have to pull content from a site that is remote to Wallabag, be it tt-rss or the original content site
3. communicate back to tt-rss in a separate action if it was successful or not. 

where is the added value by causing Wallabag to look into tt-rss?
