### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by bytersproblem** [joshp23/ttrss-to-wallabag-v2#43]
Hi!
I receive the following error 
```
2021/11/08 17:12:55 [error] 20772#20772: *588 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Controls\pluginhandler_tags() in /var/www/ttrss/plugins.local/wallabag_v2/init.php:38
```
When I enable the plugin, its section is preferences does not show any input fields.
I am not a programmer, but would like this to work.
Please help!

**EDIT**: and the stack trace
```
Stack trace:
#0 /var/www/ttrss/classes/pluginhost.php(134): Wallabag_v2->hook_prefs_tab('prefPrefs')
#1 /var/www/ttrss/classes/pref/prefs.php(982): PluginHost->run_hooks(3, 'hook_prefs_tab', 'prefPrefs')
#2 /var/www/ttrss/backend.php(110): Pref_Prefs->index()
#3 {main}
  thrown in /var/www/ttrss/plugins.local/wallabag_v2/init.php on line 38"
```

**Comment by bytersproblem** [comment]
I installed the previous release 1.10 and it works. I know that my ttrss is maybe some version older, but I didn't choose it, it came as a Yunohost version.

**Comment by joshp23** [comment]
this is a problem with Yunonhost not using the latest code and not a problem with this plugin. glad you found the solution.
