### ISSUE TITLE
[Feature request] refresh token functionality

### ISSUE THREAD

**Issue by Rurik19** [joshp23/ttrss-to-wallabag-v2#5]
It should be good not to store user password, but use refresh_token to refresh application token ( after wallabag authors fix this [issue](https://github.com/wallabag/wallabag/issues/2056)  )

**Comment by joshp23** [comment]
I agree, refresh token would be better, especially if we could set the expiry for them ourselves. however, I am assuming a large level of trust between client and server at this point, and am not to worried about it. 

At any rate, this is something I plan on looking into when I have the time. Feel free to contribute.

**Comment by joshp23** [comment]
Refresh token use was addressed with 72bde713ee799c4859cb28d0e73aff49684646d1 and username:password issue was addressed with 885d634e23e7b50875af7ac5916fdfddfd7c87b2 and is available in the [latest release](https://github.com/joshp23/ttrss-to-wallabag-v2/releases/latest)

Maybe later I will add in something to fetch OAuth on the first save.... for now, this works.

**Comment by joshp23** [comment]
username and password storage was totally removed with 11d692ae486da686ad9436e7ec532aec3c3cddab

**Comment by joshp23** [comment]
Since Wallabag refresh tokens have a limited shelf life, username:password _must_ be added back to the plugin storage here in case of refresh tokens going stale. I see no way around this. 

@Rurik19, is there any other way to refresh a refresh token other than resubmitting the username:password combo every two weeks?

**Comment by Rurik19** [comment]
Hi! I think there are some changes in the authorization process since the last release of wallabag, but I didn't look at it yet.
