### ISSUE TITLE
Password field type

### ISSUE THREAD

**Issue by Rurik19** [joshp23/ttrss-to-wallabag-v2#6]
Password input  in settings should have type="password"

**Comment by joshp23** [comment]
I don't see what you're getting at here. It already says that it is asking for your password, any more would be redundant. This data passes fine to the oauth server, and everything works well.

**Comment by Rurik19** [comment]
type="password" just means dots instead of letters in input field in settings

**Comment by joshp23** [comment]
i'll get to that as I am able. feel free to do a pull request.
